---
title: "Chapter 4 - Over-fitting and Model Tuning"
output: html_notebook
---

```{r setup}
library(caret)                      # Modeling
library(tidyverse)                  # Oppan Tidystyle
library(AppliedPredictiveModeling)  # Data sets
```

## Compute

Intersting, I didn't know a `data()` call could return two data objects!

```{r}
data(twoClassData)
classes
predictors
```

Create data partition based upon 80% of the classes.

```{r}
set.seed(1)
trainingRows <- createDataPartition(classes, p=.80, list=FALSE)
trainingRows
```

Crate training and test sets

```{r}
trainPredictors <- predictors[trainingRows, ]
trainClasses <- classes[trainingRows]
testPredictors <- predictors[-trainingRows, ]
testClasses <- classes[-trainingRows]
```

### Resampling

```{r}
set.seed(1)
repeatedSplits <- createDataPartition(trainClasses, p = 0.8, times = 3)
str(repeatedSplits)
```
10 cross folds validation

```{r}
set.seed(1)
cvSplits <- createFolds(trainClasses, k = 10, returnTrain = TRUE)
str(cvSplits)
```

## Exercises

### 4.1

